#!/bin/bash

################################################################################
# Script: optimize-limits.sh
# Description: Configures system limits for applications
# Usage: ./optimize-limits.sh --profile web [--apply]
# Author: System Administration Team
# Compatibility: RHEL 7, 8, 9
# Requirements: root
################################################################################

set -euo pipefail

# Color output functions
info() { echo -e "\033[0;36m[INFO]\033[0m $*"; }
warn() { echo -e "\033[0;33m[WARN]\033[0m $*"; }
error() { echo -e "\033[0;31m[ERROR]\033[0m $*"; }
success() { echo -e "\033[0;32m[OK]\033[0m $*"; }

# Global variables
PROFILE="default"
APPLY_MODE=0
RHEL_VERSION=""
LIMITS_DIR="/etc/security/limits.d"

# Parse arguments
parse_args() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --profile) PROFILE="$2"; shift ;;
            --apply) APPLY_MODE=1 ;;
            *) error "Unknown option: $1"; exit 1 ;;
        esac
        shift
    done
}

# Check if running as root
check_root() {
    if [[ $EUID -ne 0 ]]; then
        error "This script requires root privileges"
        exit 1
    fi
}

# Detect RHEL version
detect_rhel() {
    if [[ -f /etc/os-release ]]; then
        RHEL_VERSION=$(grep -oP '(?<=VERSION_ID=")[^"]+' /etc/os-release)
    else
        RHEL_VERSION="unknown"
    fi
}

# Get profile limits
get_profile_limits() {
    case "$PROFILE" in
        default)
            cat << 'EOF'
# Default profile limits
*	soft	nofile	1024
*	hard	nofile	65536
*	soft	nproc	4096
*	hard	nproc	4096
*	soft	memlock	unlimited
*	hard	memlock	unlimited
*	soft	core	0
*	hard	core	unlimited
*	soft	stack	8192
*	hard	stack	unlimited
EOF
            ;;
        web)
            cat << 'EOF'
# Web server profile limits
*	soft	nofile	65536
*	hard	nofile	65536
*	soft	nproc	32768
*	hard	nproc	32768
*	soft	memlock	unlimited
*	hard	memlock	unlimited
*	soft	core	0
*	hard	core	unlimited
*	soft	stack	8192
*	hard	stack	unlimited
EOF
            ;;
        database)
            cat << 'EOF'
# Database server profile limits
*	soft	nofile	65536
*	hard	nofile	65536
*	soft	nproc	65536
*	hard	nproc	65536
*	soft	memlock	unlimited
*	hard	memlock	unlimited
*	soft	core	0
*	hard	core	unlimited
*	soft	stack	unlimited
*	hard	stack	unlimited
EOF
            ;;
        high-performance)
            cat << 'EOF'
# High performance profile limits
*	soft	nofile	1048576
*	hard	nofile	1048576
*	soft	nproc	524288
*	hard	nproc	524288
*	soft	memlock	unlimited
*	hard	memlock	unlimited
*	soft	core	0
*	hard	core	unlimited
*	soft	stack	unlimited
*	hard	stack	unlimited
EOF
            ;;
        *)
            error "Unknown profile: $PROFILE"
            exit 1
            ;;
    esac
}

# Show current limits
show_current_limits() {
    info "Current system limits for user 'root':"
    echo ""

    ulimit -n | awk '{print "  Open files: " $1}'
    ulimit -u | awk '{print "  Max processes: " $1}'
    ulimit -l | awk '{print "  Locked memory: " $1}'
    ulimit -c | awk '{print "  Core file size: " $1}'
    ulimit -s | awk '{print "  Stack size: " $1}'

    echo ""
}

# Apply limits
apply_limits() {
    info "Applying $PROFILE profile limits..."

    mkdir -p "$LIMITS_DIR"

    local config_file="${LIMITS_DIR}/99-custom-limits.conf"

    {
        echo "# System limits - $PROFILE profile"
        echo "# Generated by optimize-limits.sh on $(date '+%Y-%m-%d %H:%M:%S')"
        echo ""
        get_profile_limits
    } > "$config_file"

    chmod 644 "$config_file"
    success "Configuration applied to: $config_file"

    cat "$config_file"
}

# Validate limits configuration
validate_limits() {
    echo ""
    info "Validating limits configuration..."

    if [[ ! -d "$LIMITS_DIR" ]]; then
        error "Limits directory not found: $LIMITS_DIR"
        return 1
    fi

    local config_file="${LIMITS_DIR}/99-custom-limits.conf"
    if [[ ! -f "$config_file" ]]; then
        warn "Configuration file not found: $config_file"
        return 1
    fi

    # Check syntax
    if grep -qE "^[*@][[:space:]]+soft|^[*@][[:space:]]+hard" "$config_file"; then
        success "Configuration syntax is valid"
        return 0
    else
        error "Configuration has invalid syntax"
        return 1
    fi
}

# Show kernel limits
show_kernel_limits() {
    echo ""
    info "Kernel system limits:"
    echo ""

    local file_max=$(cat /proc/sys/fs/file-max)
    local pid_max=$(cat /proc/sys/kernel/pid_max)

    success "  fs.file-max: $file_max"
    success "  kernel.pid_max: $pid_max"

    echo ""
}

# List available profiles
list_profiles() {
    echo ""
    info "Available profiles:"
    echo "  - default (minimal)"
    echo "  - web (web servers)"
    echo "  - database (database servers)"
    echo "  - high-performance (maximum limits)"
    echo ""
}

# Check per-user limits
check_user_limits() {
    local username="$1"

    echo ""
    info "Limits for user: $username"

    if id "$username" > /dev/null 2>&1; then
        # Create temporary script to check limits as the user
        local temp_script=$(mktemp)
        cat > "$temp_script" << 'EOF'
#!/bin/bash
echo "  Open files: $(ulimit -n)"
echo "  Max processes: $(ulimit -u)"
echo "  Locked memory: $(ulimit -l)"
echo "  Core file size: $(ulimit -c)"
echo "  Stack size: $(ulimit -s)"
EOF
        chmod +x "$temp_script"
        su - "$username" -c "$temp_script" 2>/dev/null || warn "Could not check limits for $username"
        rm -f "$temp_script"
    else
        warn "User not found: $username"
    fi
}

# Main execution
main() {
    parse_args "$@"
    check_root
    detect_rhel

    {
        info "=== System Limits Optimizer ==="
        info "RHEL Version: $RHEL_VERSION"
        info "Profile: $PROFILE"
        info "Timestamp: $(date '+%Y-%m-%d %H:%M:%S')"
        echo ""

        show_current_limits
        show_kernel_limits
        list_profiles
        echo ""

        if [[ $APPLY_MODE -eq 1 ]]; then
            apply_limits
            echo ""
            validate_limits
            echo ""
            success "Limits profile applied. Log out and back in for changes to take effect."
        else
            info "Preview of $PROFILE profile:"
            echo ""
            get_profile_limits
            echo ""
            info "Use --apply to apply these limits"
        fi
    }
}

main "$@"
