#!/bin/bash

################################################################################
# Script: tune-kernel.sh
# Description: Applies kernel tuning parameters via sysctl
# Usage: ./tune-kernel.sh --profile web-server [--apply] [--audit] [--revert]
# Author: System Administration Team
# Compatibility: RHEL 7, 8, 9
# Requirements: root, sysctl
################################################################################

set -euo pipefail

# Color output functions
info() { echo -e "\033[0;36m[INFO]\033[0m $*"; }
warn() { echo -e "\033[0;33m[WARN]\033[0m $*"; }
error() { echo -e "\033[0;31m[ERROR]\033[0m $*"; }
success() { echo -e "\033[0;32m[OK]\033[0m $*"; }

# Global variables
PROFILE="general"
APPLY_MODE=0
AUDIT_MODE=0
REVERT_MODE=0
RHEL_VERSION=""
SYSCTL_CONFIG="/etc/sysctl.conf"
BACKUP_DIR="/var/backups"
BACKUP_FILE="${BACKUP_DIR}/sysctl.backup.$(date '+%Y%m%d-%H%M%S')"

# Parse arguments
parse_args() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --profile) PROFILE="$2"; shift ;;
            --apply) APPLY_MODE=1 ;;
            --audit) AUDIT_MODE=1 ;;
            --revert) REVERT_MODE=1 ;;
            *) error "Unknown option: $1"; exit 1 ;;
        esac
        shift
    done
}

# Check if running as root
check_root() {
    if [[ $EUID -ne 0 ]]; then
        error "This script requires root privileges"
        exit 1
    fi
}

# Detect RHEL version
detect_rhel() {
    if [[ -f /etc/os-release ]]; then
        RHEL_VERSION=$(grep -oP '(?<=VERSION_ID=")[^"]+' /etc/os-release)
    else
        RHEL_VERSION="unknown"
    fi
}

# Define tuning profiles
get_profile_params() {
    case "$PROFILE" in
        web-server)
            cat << 'EOF'
# Web Server Profile
net.core.somaxconn=4096
net.ipv4.tcp_max_syn_backlog=8096
net.ipv4.ip_local_port_range=1024 65535
net.ipv4.tcp_fin_timeout=30
net.ipv4.tcp_tw_reuse=1
net.core.netdev_max_backlog=5000
vm.swappiness=10
EOF
            ;;
        database)
            cat << 'EOF'
# Database Profile
vm.swappiness=5
vm.dirty_ratio=10
vm.dirty_background_ratio=5
kernel.shmmax=17179869184
kernel.shmall=4194304
net.core.rmem_max=134217728
net.core.wmem_max=134217728
net.ipv4.tcp_rmem=4096 87380 134217728
net.ipv4.tcp_wmem=4096 65536 134217728
EOF
            ;;
        general)
            cat << 'EOF'
# General Purpose Profile
kernel.sysrq=1
kernel.panic=10
kernel.panic_on_oops=1
vm.swappiness=30
fs.file-max=2097152
net.ipv4.conf.all.send_redirects=0
net.ipv4.conf.all.accept_redirects=0
net.ipv4.icmp_echo_ignore_all=0
EOF
            ;;
        high-performance)
            cat << 'EOF'
# High Performance Profile
net.core.somaxconn=8192
net.ipv4.tcp_max_syn_backlog=16384
vm.swappiness=0
vm.dirty_ratio=15
vm.dirty_background_ratio=10
net.core.rmem_max=536870912
net.core.wmem_max=536870912
fs.file-max=4194304
kernel.pid_max=4194304
EOF
            ;;
        *)
            error "Unknown profile: $PROFILE"
            exit 1
            ;;
    esac
}

# Backup current sysctl settings
backup_settings() {
    mkdir -p "$BACKUP_DIR"

    info "Backing up current settings to: $BACKUP_FILE"
    sysctl -a > "$BACKUP_FILE"

    success "Backup created"
}

# Apply sysctl parameters
apply_parameters() {
    local params=$(get_profile_params)

    info "Applying $PROFILE profile parameters..."

    while IFS= read -r line; do
        # Skip comments and empty lines
        [[ "$line" =~ ^# ]] && continue
        [[ -z "$line" ]] && continue

        local key=$(echo "$line" | awk '{print $1}')
        local value=$(echo "$line" | awk '{print $2}')

        if sysctl -w "$key=$value" > /dev/null 2>&1; then
            success "  Applied: $key = $value"
        else
            warn "  Failed to apply: $key"
        fi
    done <<< "$params"
}

# Persist parameters
persist_parameters() {
    local params=$(get_profile_params)
    local config_dir="/etc/sysctl.d"

    info "Persisting parameters to $config_dir..."

    mkdir -p "$config_dir"

    local config_file="${config_dir}/99-custom-tuning.conf"

    {
        echo "# Kernel tuning - $PROFILE profile"
        echo "# Generated by tune-kernel.sh on $(date '+%Y-%m-%d %H:%M:%S')"
        echo ""
        echo "$params"
    } > "$config_file"

    success "Configuration saved to: $config_file"
}

# Audit current parameters
audit_parameters() {
    info "=== Current Kernel Parameters ==="
    echo ""

    local params=$(get_profile_params)

    while IFS= read -r line; do
        [[ "$line" =~ ^# ]] && { echo "$line"; continue; }
        [[ -z "$line" ]] && continue

        local key=$(echo "$line" | awk '{print $1}')
        local expected_value=$(echo "$line" | awk '{print $2}')
        local current_value=$(sysctl -n "$key" 2>/dev/null || echo "NOT FOUND")

        if [[ "$current_value" == "$expected_value" ]]; then
            success "  ✓ $key = $current_value"
        else
            warn "  ✗ $key = $current_value (expected: $expected_value)"
        fi
    done <<< "$params"

    echo ""
}

# Show current values
show_current_values() {
    info "Current important kernel parameters:"
    echo ""

    local important_params=(
        "vm.swappiness"
        "net.core.somaxconn"
        "net.ipv4.tcp_max_syn_backlog"
        "fs.file-max"
        "kernel.pid_max"
        "vm.dirty_ratio"
        "net.ipv4.tcp_tw_reuse"
    )

    for param in "${important_params[@]}"; do
        local value=$(sysctl -n "$param" 2>/dev/null || echo "N/A")
        info "  $param = $value"
    done

    echo ""
}

# Revert to backup
revert_settings() {
    if [[ ! -f "$BACKUP_FILE" ]]; then
        error "Backup file not found: $BACKUP_FILE"
        exit 1
    fi

    info "Reverting to backup: $BACKUP_FILE"

    while IFS='=' read -r key value; do
        key=$(echo "$key" | xargs)
        value=$(echo "$value" | xargs)

        [[ -z "$key" ]] && continue
        [[ "$key" =~ ^# ]] && continue

        sysctl -w "$key=$value" > /dev/null 2>&1 || true
    done < "$BACKUP_FILE"

    success "Settings reverted"
}

# Validate changes
validate_changes() {
    info "Validating kernel parameter changes..."

    if sysctl -a > /dev/null 2>&1; then
        success "System validation passed"
        return 0
    else
        error "System validation failed"
        return 1
    fi
}

# Main execution
main() {
    parse_args "$@"
    check_root
    detect_rhel

    {
        info "=== Kernel Tuning Manager ==="
        info "RHEL Version: $RHEL_VERSION"
        info "Profile: $PROFILE"
        info "Timestamp: $(date '+%Y-%m-%d %H:%M:%S')"
        echo ""

        if [[ $REVERT_MODE -eq 1 ]]; then
            revert_settings
            echo ""
            show_current_values
        elif [[ $AUDIT_MODE -eq 1 ]]; then
            audit_parameters
            show_current_values
        elif [[ $APPLY_MODE -eq 1 ]]; then
            backup_settings
            echo ""
            apply_parameters
            echo ""
            persist_parameters
            echo ""
            validate_changes
            echo ""
            info "Profile applied. Reboot recommended for full effect."
        else
            show_current_values
            echo ""
            info "Use --apply to apply profile changes"
            info "Use --audit to compare current vs. profile"
            info "Use --revert to restore from backup"
        fi
    }
}

main "$@"
