#!/bin/bash

################################################################################
# Script: journal-cleanup.sh
# Description: Manages systemd journal size and configuration
# Usage: ./journal-cleanup.sh [--max-size 1G] [--max-time 30d] [--show]
# Author: System Administration Team
# Compatibility: RHEL 7.4+, 8, 9 (requires systemd-journal)
# Requirements: root, systemd-journal
################################################################################

set -euo pipefail

# Color output functions
info() { echo -e "\033[0;36m[INFO]\033[0m $*"; }
warn() { echo -e "\033[0;33m[WARN]\033[0m $*"; }
error() { echo -e "\033[0;31m[ERROR]\033[0m $*"; }
success() { echo -e "\033[0;32m[OK]\033[0m $*"; }

# Global variables
MAX_SIZE=""
MAX_TIME=""
SHOW_MODE=0
RHEL_VERSION=""
JOURNAL_CONFIG="/etc/systemd/journald.conf"
JOURNAL_CONFIG_DIR="/etc/systemd/journald.conf.d"

# Parse arguments
parse_args() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --max-size) MAX_SIZE="$2"; shift ;;
            --max-time) MAX_TIME="$2"; shift ;;
            --show) SHOW_MODE=1 ;;
            *) error "Unknown option: $1"; exit 1 ;;
        esac
        shift
    done
}

# Check if running as root
check_root() {
    if [[ $EUID -ne 0 ]]; then
        error "This script requires root privileges"
        exit 1
    fi
}

# Detect RHEL version
detect_rhel() {
    if [[ -f /etc/os-release ]]; then
        RHEL_VERSION=$(grep -oP '(?<=VERSION_ID=")[^"]+' /etc/os-release)
    else
        RHEL_VERSION="unknown"
    fi
}

# Check journalctl availability
check_journalctl() {
    if ! command -v journalctl &> /dev/null; then
        error "journalctl is not available"
        exit 1
    fi
    success "journalctl is available"
}

# Show current journal usage
show_journal_usage() {
    info "=== Current Journal Usage ==="
    echo ""

    # Get journal statistics
    local journal_path="/var/log/journal"
    if [[ -d "$journal_path" ]]; then
        local total_size=$(du -sh "$journal_path" 2>/dev/null | awk '{print $1}')
        local file_count=$(find "$journal_path" -type f 2>/dev/null | wc -l)

        info "Journal location: $journal_path"
        success "Total size: $total_size"
        info "Total files: $file_count"
    else
        warn "Journal directory not found: $journal_path"
    fi

    echo ""
    info "Journal statistics from journalctl:"
    journalctl --disk-usage 2>/dev/null || warn "Could not retrieve disk usage"

    echo ""
    info "Current journal configuration:"
    if [[ -f "$JOURNAL_CONFIG" ]]; then
        grep -E "^[^#]" "$JOURNAL_CONFIG" | grep -iE "max|retention|runtime|vacuum" || info "No size/retention settings configured"
    else
        info "Default configuration in use"
    fi
}

# Show journal oldest and newest entries
show_journal_timeline() {
    echo ""
    info "Journal timeline:"

    if journalctl --no-pager --quiet -n 1 &>/dev/null; then
        success "Newest entry:"
        journalctl --no-pager -n 1 --output=short 2>/dev/null | tail -1 || true

        success "Oldest entry:"
        journalctl --no-pager --reverse -n 1 --output=short 2>/dev/null | head -1 || true
    fi
}

# Configure journal retention
configure_journal() {
    info "=== Configuring Journal Retention ==="
    echo ""

    # Create drop-in directory if needed
    if [[ ! -d "$JOURNAL_CONFIG_DIR" ]]; then
        mkdir -p "$JOURNAL_CONFIG_DIR"
        success "Created: $JOURNAL_CONFIG_DIR"
    fi

    # Create custom configuration file
    local custom_config="${JOURNAL_CONFIG_DIR}/99-custom-retention.conf"
    info "Creating configuration: $custom_config"

    {
        echo "# Custom journal retention configuration"
        echo "# Generated by journal-cleanup.sh on $(date '+%Y-%m-%d %H:%M:%S')"
        echo "[Journal]"

        if [[ -n "$MAX_SIZE" ]]; then
            echo "SystemMaxUse=$MAX_SIZE"
            echo "RuntimeMaxUse=$MAX_SIZE"
            info "Setting SystemMaxUse: $MAX_SIZE"
        fi

        if [[ -n "$MAX_TIME" ]]; then
            echo "MaxRetentionSec=$MAX_TIME"
            info "Setting MaxRetentionSec: $MAX_TIME"
        fi

        # Best practices
        echo "SystemMaxFileSize=\$(( \$(grep SystemMaxUse /etc/systemd/journald.conf.d/99-custom-retention.conf 2>/dev/null | cut -d= -f2 | numfmt --from=iec 2>/dev/null || echo 1073741824) / 10 ))"
        echo "StandardOutput=journal"
        echo "StandardError=journal"
    } > "$custom_config"

    success "Configuration created: $custom_config"
    cat "$custom_config"

    echo ""
    info "Reloading systemd-journald service..."
    systemctl restart systemd-journald
    success "Service restarted"
}

# Perform journal vacuum
vacuum_journal() {
    info "=== Vacuuming Journal ==="
    echo ""

    info "Running journalctl --vacuum-time=30d..."
    journalctl --vacuum-time=30d 2>/dev/null || warn "Vacuum time operation may have failed"

    if [[ -n "$MAX_SIZE" ]]; then
        info "Running journalctl --vacuum-size=$MAX_SIZE..."
        journalctl --vacuum-size="$MAX_SIZE" 2>/dev/null || warn "Vacuum size operation may have failed"
    fi

    echo ""
    success "Journal vacation complete"
}

# Verify journal permissions
verify_permissions() {
    echo ""
    info "=== Verifying Journal Permissions ==="

    local journal_path="/var/log/journal"
    if [[ -d "$journal_path" ]]; then
        local perms=$(stat -c '%a' "$journal_path")
        info "Journal directory permissions: $perms"

        if [[ "$perms" != "755" ]]; then
            warn "Non-standard permissions detected"
        fi
    fi

    # Check if journal is being stored persistently
    if [[ ! -d "$journal_path" ]]; then
        warn "Journal is in volatile mode (lost on reboot)"
        warn "To enable persistent storage: mkdir -p /var/log/journal && systemctl restart systemd-journald"
    else
        success "Journal is in persistent mode"
    fi
}

# Main execution
main() {
    parse_args "$@"
    check_root
    detect_rhel
    check_journalctl

    {
        info "=== Journal Cleanup Manager ==="
        info "RHEL Version: $RHEL_VERSION"
        info "Timestamp: $(date '+%Y-%m-%d %H:%M:%S')"
        echo ""

        if [[ $SHOW_MODE -eq 1 ]]; then
            show_journal_usage
            show_journal_timeline
        else
            show_journal_usage
            echo ""
            configure_journal
            echo ""
            verify_permissions

            if [[ -z "$MAX_SIZE" && -z "$MAX_TIME" ]]; then
                info "No size/time limits specified. Run with --show to view current usage."
            else
                echo ""
                vacuum_journal
            fi
        fi
    }
}

main "$@"
