#!/bin/bash

################################################################################
# Script: setup-logrotate.sh
# Description: Creates or audits logrotate configurations
# Usage: ./setup-logrotate.sh --path /var/log/app.log [--rotate 7] [--size 100M] [--compress] [--audit]
# Author: System Administration Team
# Compatibility: RHEL 7, 8, 9
# Requirements: root, logrotate
################################################################################

set -euo pipefail

# Color output functions
info() { echo -e "\033[0;36m[INFO]\033[0m $*"; }
warn() { echo -e "\033[0;33m[WARN]\033[0m $*"; }
error() { echo -e "\033[0;31m[ERROR]\033[0m $*"; }
success() { echo -e "\033[0;32m[OK]\033[0m $*"; }

# Global variables
LOG_PATH=""
ROTATE_COUNT=7
ROTATE_SIZE="100M"
COMPRESS=1
AUDIT_MODE=0
RHEL_VERSION=""
CONFIG_DIR="/etc/logrotate.d"

# Parse arguments
parse_args() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --path) LOG_PATH="$2"; shift ;;
            --rotate) ROTATE_COUNT="$2"; shift ;;
            --size) ROTATE_SIZE="$2"; shift ;;
            --compress) COMPRESS=1 ;;
            --no-compress) COMPRESS=0 ;;
            --audit) AUDIT_MODE=1 ;;
            *) error "Unknown option: $1"; exit 1 ;;
        esac
        shift
    done
}

# Check if running as root
check_root() {
    if [[ $EUID -ne 0 ]]; then
        error "This script requires root privileges"
        exit 1
    fi
}

# Detect RHEL version
detect_rhel() {
    if [[ -f /etc/os-release ]]; then
        RHEL_VERSION=$(grep -oP '(?<=VERSION_ID=")[^"]+' /etc/os-release)
    else
        RHEL_VERSION="unknown"
    fi
}

# Check logrotate availability
check_logrotate() {
    if ! command -v logrotate &> /dev/null; then
        error "logrotate is not installed"
        exit 1
    fi
    success "logrotate is available"
}

# Validate log path
validate_log_path() {
    if [[ -z "$LOG_PATH" ]]; then
        error "Log path is required (use --path)"
        exit 1
    fi

    if [[ ! -f "$LOG_PATH" ]]; then
        warn "Log file does not exist: $LOG_PATH"
        info "Config will be created anyway for future use"
    else
        success "Log file found: $LOG_PATH"
    fi
}

# Create logrotate configuration
create_config() {
    local config_name=$(basename "$LOG_PATH" | tr '.' '_')
    local config_file="${CONFIG_DIR}/${config_name}"

    info "Creating logrotate config: $config_file"

    local compress_opt=""
    if [[ $COMPRESS -eq 1 ]]; then
        compress_opt="    compress
    delaycompress"
    fi

    cat > "$config_file" << EOF
# Logrotate configuration for $LOG_PATH
# Generated by setup-logrotate.sh on $(date '+%Y-%m-%d %H:%M:%S')

$LOG_PATH {
    size $ROTATE_SIZE
    rotate $ROTATE_COUNT
    missingok
    notifempty
    create 0640 root root$compress_opt
    dateext
    dateformat -%Y%m%d
    sharedscripts
    postrotate
        /bin/kill -SIGHUP \$(cat /var/run/syslogd.pid 2>/dev/null) 2>/dev/null || true
        /bin/kill -SIGHUP \$(cat /var/run/rsyslogd.pid 2>/dev/null) 2>/dev/null || true
    endscript
}
EOF

    if [[ -f "$config_file" ]]; then
        success "Config created: $config_file"
        chmod 644 "$config_file"
    else
        error "Failed to create config file"
        exit 1
    fi
}

# Audit existing logrotate configurations
audit_configs() {
    info "=== Logrotate Configuration Audit ==="
    echo ""

    local config_count=0
    local issue_count=0

    for config in "${CONFIG_DIR}"/*; do
        [[ ! -f "$config" ]] && continue

        config_count=$((config_count + 1))
        info "Checking: $(basename "$config")"

        # Check for common issues
        if ! grep -q "rotate" "$config" 2>/dev/null; then
            warn "  Missing 'rotate' directive"
            issue_count=$((issue_count + 1))
        fi

        if ! grep -q "missingok" "$config" 2>/dev/null; then
            warn "  Missing 'missingok' directive (log file may not exist)"
            issue_count=$((issue_count + 1))
        fi

        if ! grep -qE "size|daily|weekly|monthly" "$config" 2>/dev/null; then
            warn "  No rotation trigger (size, daily, weekly, or monthly)"
            issue_count=$((issue_count + 1))
        fi

        # Check permissions
        local perms=$(stat -c '%a' "$config")
        if [[ "$perms" != "644" ]]; then
            warn "  Unusual permissions: $perms (should be 644)"
            issue_count=$((issue_count + 1))
        fi
    done

    echo ""
    success "Configs checked: $config_count"
    if [[ $issue_count -gt 0 ]]; then
        warn "Issues found: $issue_count"
    else
        success "No issues found"
    fi
}

# Test logrotate configuration
test_config() {
    info "Testing logrotate configuration..."

    if logrotate -d "${CONFIG_DIR}/"* 2>&1 | grep -q "error"; then
        error "Logrotate test failed"
        logrotate -d "${CONFIG_DIR}/"* 2>&1 | head -20
        return 1
    else
        success "Logrotate test passed"
        return 0
    fi
}

# Show logrotate status
show_status() {
    info "=== Logrotate Status ==="
    echo ""

    local config_count=$(find "${CONFIG_DIR}" -type f | wc -l)
    success "Total configurations: $config_count"

    if [[ -f /var/lib/logrotate/status ]]; then
        info "Last logrotate run:"
        tail -5 /var/lib/logrotate/status | awk '{print "  " $0}'
    else
        warn "No logrotate status file found (logrotate may not have run yet)"
    fi
}

# Main execution
main() {
    parse_args "$@"
    check_root
    detect_rhel
    check_logrotate

    {
        info "=== Logrotate Configuration Manager ==="
        info "RHEL Version: $RHEL_VERSION"
        info "Timestamp: $(date '+%Y-%m-%d %H:%M:%S')"
        echo ""

        if [[ $AUDIT_MODE -eq 1 ]]; then
            audit_configs
            echo ""
            test_config
            echo ""
            show_status
        else
            validate_log_path
            echo ""
            create_config
            echo ""
            test_config
            echo ""
            info "Logrotate configuration complete"
        fi
    }
}

main "$@"
